version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # noinspection ComposeUnknownValues
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    #ports:
      #- "5432:5432"    # необязательно, для внешнего доступа
    networks:
      - movie-net

  web-app:
    build: .
    container_name: go-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db                # имя сервиса (не localhost!)
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
      DB_SSLMODE: disable
    ports:
      - "8000:8080"              # наружу 8000, внутри 8080
    networks:
      - movie-net

volumes:
  postgres_data:

networks:
  movie-net:
    driver: bridge